# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('image_thubnail', models.ImageField(height_field=200, upload_to='gallery/thubnail/', width_field=360)),
                ('image_fullsize', models.ImageField(upload_to='gallery/full_size/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
