# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_thubnail',
            field=models.ImageField(upload_to='gallery/thubnail/'),
        ),
    ]
